### ISSUE TITLE
[DataCap Application] Asia Television Limited

### ISSUE THREAD

**Issue by MayFBWY** [fidlabs/Enterprise-Data-Pathway#10]
### Version

1

### DataCap Applicant

Asia Television Limited

### What is your role related to the dataset

Dataset Owner

### Project ID

2256

### Data Owner Name

Asia Television Limited

### Data Owner Country/Region

Hong Kong

### Data Owner Industry

Arts & Recreation

### Website

http://www.hkatv.com/

### Social Media Handle

https://www.youtube.com/atvhongkong

### Social Media Type

Other

### Total amount of DataCap being requested

50 PiB

### Unit for total amount of DataCap being requested

PiB

### Expected size of single dataset (one copy)

15 PiB

### Unit for expected size of single dataset

PiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### Unit for weekly allocation of DataCap requested

PiB

### On-chain address for first allocation

f1zqxtp66woilzxlbvdlixnm5yttimhhokpq65wja

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Asia Television Limited (Chinese: 亞洲電視有限公司, also known as ATV) is a digital media and broadcasting company in Hong Kong. Established as the first television service in Hong Kong as Rediffusion Television (Chinese: 麗的電視/麗的呼聲) on 29 May 1957, it shifted to terrestrial television on 30 November 1973, and was renamed Asia Television on 24 September 1982. ATV operated two main over-the-air channels: the Cantonese-language ATV Home and the English-language ATV World.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Videos, films and other recordings created or belongs to Asia Television Limited.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
http://www.hkatv.com/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### If you chose not to confirm, what was the reason

```text
This application is an E-FIL+ program.
```

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How did you find your storage providers

Slack, Filmine, Big Data Exchange, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
SP List provided:
[{"providerID": "f02001777 ", "City": "Hu Nan", "Country": "CN", "SPOrg","Rightwing "},
{"providerID": "f02104858 ", "City": "HK", "Country": "CN","SPOrg","XYZ"},
{"providerID": "f02006999 ", "City": "HK", "Country": "CN","SPOrg","XYZ"},
{"providerID": "f0134516 ", "City": "HK", "Country": "CN","SPOrg","XL Network"},
{"providerID": "f02003866 ", "City": "XYZ", "Country": "Singapore","SPOrg","KY Tech"},
{"providerID": "f02003888 ", "City": "XYZ", "Country": "Singapore","SPOrg","IPFS Force"},
{"providerID": "f0118330 ", "City": "HK", "Country": "CN","SPOrg","XYZ"},
{"providerID": "f02809368 ", "City": "XYZ", "Country": "Japan","SPOrg","XYZ"},
{"providerID": "f02002888 ", "City": "XYZ", "Country": "Japan","SPOrg","XYZ"},]
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by kevzak** [comment]
@MayFBWY as part of diligence for this application please complete:


- Github User KYC Check (https://filplus.storage/) and login and select KYC from drop down.
- KYB Form ([LINK](https://github.com/fidlabs/Enterprise-Data-Pathway/issues/url))

**Comment by kevzak** [comment]
@MayFBWY in this pathway unfortunately you cannot request 50PiB and 1PiB/week to start as a new client. 

50TiB can be your first allocation and after you can apply for 5 PiBs. I will reset your values

**Comment by kevzak** [comment]
client never replied with required info, closing for now
