### ISSUE TITLE
[DataCap Application] Rebel Iron - AI Datasets

### ISSUE THREAD

**Issue by Trevor-K-Smith** [fidlabs/Enterprise-Data-Pathway#16]
### Version

1

### DataCap Applicant

Global Stake

### Project ID

2442

### Data Owner Name

Rebel Iron

### Data Owner Country/Region

United States

### Data Owner Industry

IT & Technology Services

### Website

https://rebeliron.com/

### Social Media Handle

Trevor K Smith

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

25PiB

### Expected size of single dataset (one copy)

5PiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

1000TiB

### On-chain address for first allocation

f1dcjmawlolcjiupvmjr2j6bce3eb77rrtwjtx2sq

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
At Rebel Iron, we focus on providing managed infrastructure that's ideal for AI and Web3 applications. We pride ourselves on delivering solutions that are decentralized, secure, and efficient, meeting the needs of institutions and enterprises worldwide. Our expertise lies in leveraging cutting-edge technology to support demanding AI workloads, making us adept at handling large-scale data storage projects on platforms like Filecoin.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
We're teaming up with our partner Global Stake for data preparation, focusing on handling and organizing extensive datasets for our projects. This collaboration is crucial for optimizing the data for storage and use, especially on platforms like Filecoin, ensuring we provide the best possible infrastructure for AI and Web3 applications.
```

### Describe the data being stored onto Filecoin

```text
The data we're storing has been carefully scraped from the internet, focusing on specific topics that our clients are interested in for AI training. Typically includes scrapped data from Reddit, Wiki, and google search results.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

United States

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Global Stake

https://singularity.storage/

Have used in past for data preparation.
```

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
Trevor K Smith

Global Stake
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
No.

Will be stored among 5 different provides. Will source additional providers on Filecoin Slack as needed.
```

### Please share a sample of the data

```text
https://i.imgur.com/pTxJvoi.png

The above is an areal photo of a house, which is being used on a internal client project for developing real estate AI tools.
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### If you chose not to confirm, what was the reason

```text
Can be retrieved by anyone but will be encrypted.
```

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```
List will be updated with additional providers when avalible.

1) f01091851 Kansas
2) f01385207 Kansas
3) f01820744 NA 
4) f01908299 Washington DC
5) f01736668 NA
6) f01794610 NA
7) f01840436 NA


```

### How do you plan to make deals to your storage providers

Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by kevzak** [comment]
Hi @Trevor-K-Smith - thanks for applying. 

Next steps required are:
-Github User KYC Check (https://filplus.storage/) and login and select KYC from drop down.
-KYB Form ([LINK](https://github.com/fidlabs/Enterprise-Data-Pathway/issues/url))

Feel free to reach out on slack with Qs.

**Comment by kevzak** [comment]
Also please note - as a trusted contact, you're eligible for 5PiB of DataCap for your first application in this pathway. With the following allocation schedule:
5%
15%
30%
50%

Assuming diligence checks go well, you can then request the additional 20PiBs.

**Comment by Trevor-K-Smith** [comment]
Closing this and will reopen. Wanting to clarify and change some details on the application after syncing with team for this project.
