### ISSUE TITLE
[DataCap Application] <KABAT> - <MOTOWIZJA>

### ISSUE THREAD

**Issue by FILDCKabat** [fidlabs/Enterprise-Data-Pathway#3]
### Version

1

### DataCap Applicant

FILDCKabat 

### Project ID

#928

### Data Owner Name

AGENCJA PROMOCJI MOTORYZACJI A.P.M.AUTO

### Data Owner Country/Region

Poland

### Data Owner Industry

Information, Media & Telecommunications

### Website

https://motowizja.pl/

### Social Media Handle

https://www.facebook.com/motowizja

### Social Media Type

Facebook

### What is your role related to the dataset

Storage provider filling out application on behalf of owner

### Total amount of DataCap being requested

4.32

### Unit for total amount of DataCap being requested

PiB

### Expected size of single dataset (one copy)

720

### Unit for expected size of single dataset

TiB

### Number of replicas to store

6

### Weekly allocation of DataCap requested

100

### Unit for weekly allocation of DataCap requested

TiB

### On-chain address for first allocation

f1ieughpsgkdynelb2tipfpuhdvcvltfvsuv54q2q

### Data Type of Application

Slingshot

### Custom multisig

- [X] Use Custom Multisig

### Identifier

f01940930

### Share a brief history of your project and organization

```text
AGENCJA PROMOCJI MOTORYZACJI A.P.M.AUTO makes motorsport movies for over 20 years, we have been doing motorsport content for different televisions and also for private competitors, as well as for YouTube's channels. For today we make realizations mainly for Motowizja televisions which is the biggest motorsport one in Poland. We would like to store our big archives.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
movie files
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Poland

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We receive encrypted data which we prepare using singularity
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
We are while the process of storing data, hasn't finished it yet. Project has started 5 Sep 2022
Six full replicas, 6 x 720TiB = 4.32PiB [PiB] of Datacap

Primary SP Partner:
f02927579 | KABAT OU/FILDC | Poland, Łódź, Europe
f02770730 | KABAT OU/FILDC | Poland, Poznań, Europe
f01619524 | Flux Storage Pte. Ltd | Germany, Frankfurt am Main, Europe
f099608 | Private/Stander | Latvia, Riga, Europe
f020378 | Web3 providers LLC | Bulgaria, Asenovgrad, Europe 
unknown | PiKNiK | Las Vegas, USA


```

### Please share a sample of the data

```text
(https://www.youtube.com/watch?v=qfoQqS2a4ck) this is an example of ready, short movie, but mainly we 30min programs and we like to store all uncut files, which are many times bigger.
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### If you chose not to confirm, what was the reason

```text
NO, there is no problem to show what type of files we are going to store but we like to get files encrypted at the final stage.
```

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Europe

### How will you be distributing your data to storage providers

Venus built-in data transfer

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
Six full replicas, 6 x 720TiB = 4.2PiB [PiB]

Primary SP Partner:
FILDC (f01127678, f02097113, f02218935, f02239603)
Location: Europe, Poland:
-> Poznan: f01127678, f02770730
-> Lodz: f02239603, f02097113, f02817132, f02218935

Additional replica's partners:
DSS, Australia (f01919423, f01938357)
DCENT, Europe, Netherlands (f02033496, f01771403)
Hong Kong Morpho Technology Limited, Hong Kong (f01989888, f01926635, f01933917, f01885088, f02058048, f01999119)
Saturnia, Russian Federation (f08240, f0187709, f01222595)
Pride Holdings, UAE, Dubai (f01907556)
PiKNiK, USA, Las Vegas (f01851060)
Flux Storage Pte. Ltd, Europe, Germany (f01619524)
Web3 providers LLC, Europe, Bulgaria (f020378)
Stander, Europe, Latvia (f099608)
```

### How do you plan to make deals to your storage providers

Boost client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by kevzak** [comment]
@FILDCKabat you need to edit the data points regarding the dataset size and number of copies.

**Comment by kevzak** [comment]
@FILDCKabat please complete the KYC check on your GitHub ID on filplus.storage login

Also, please complete this KYB form with details about the applicant and client: https://form.jotform.com/240786057753667

**Comment by kevzak** [comment]
I can confirm KYC was completed https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/928#issuecomment-2009414386

**Comment by FILDCKabat** [comment]
> @FILDCKabat please complete the KYC check on your GitHub ID on filplus.storage login
> 
> Also, please complete this KYB form with details about the applicant and client: https://form.jotform.com/240786057753667

done

**Comment by kevzak** [comment]
@FILDCKabat your plan is 8 full replicas of 5PiB dataset? So 40 PiB total? 

Why are you asking for only 5 PiB?

Please provide some proof of dataset size.

**Comment by kevzak** [comment]
@FILDCKabat also update the Data type field. 'Slingshot' is not an option, I need to remove from dropdown.

**Comment by FILDCKabat** [comment]
> @FILDCKabat in the application is says your plan is 8 full replicas of 5PiB dataset? So 40 PiB total?
> 
> Why are you asking for only 5 PiB and 4 copies?
> 
> In your previous application you stored data, does this count toward the total already? https://github.com/data-preservation-programs/filplus-checker-assets/blob/main/filecoin-project/filecoin-plus-large-datasets/issues/928/1710874625875.md
> 
> Finally, once clear, Please provide some proof of dataset size.

changed
finally it's 6 x 720TiB

**Comment by FILDCKabat** [comment]
> owner

owner is AGENCJA PROMOCJI MOTORYZACJI A.P.M.AUTO and it's exactly this is application

**Comment by kevzak** [comment]
> > owner
> 
> owner is AGENCJA PROMOCJI MOTORYZACJI A.P.M.AUTO and it's exactly this is application

This question has incorrect answer, i will update: 
<img width="597" alt="image" src="https://github.com/fidlabs/Enterprise-Data-Pathway/assets/102751751/271bc27d-6fc8-471e-b49d-0c8c79d1d130">

**Comment by kevzak** [comment]
We've issues 5% (200TiB) @donkabat. When you are close to using it all, we can review and then issue the next tranche, 15%.

**Comment by kevzak** [comment]
Note: This application is being closed because the client address is the same as from an EFIL LDN application for this project.

Per our guidelines, as a known user, this client was awarded 5% of their request (200TiB) in this application.

The client will use a new address and future allocations can be seen in https://github.com/fidlabs/Enterprise-Data-Pathway/issues/18

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by dampud** [comment]
Closed due to inactivity
