### ISSUE TITLE
[DataCap Application] <Cloud Era Cloud Monitoring> - <AI Intelligent Recognition>

### ISSUE THREAD

**Issue by Zzbaoo** [fidlabs/Enterprise-Data-Pathway#67]
### Data Owner Name

Bond

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

http://www.gdysd.cn/

### Social Media Handle

hpjnba@gmail.com

### Social Media Type

Other

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

6PiB

### Expected size of single dataset (one copy)

1PiB

### Number of replicas to store

6

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1c7g4s72syxnpu5v6t5odqvkgpc5oyaub5lgi3ii

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [X] Use Custom Multisig

### Share a brief history of your project and organization

```text
Cloud Era Cloud Monitoring Project:
Currently, we are a professional digital upgrade service provider and operator for the retail industry. Our focus is on providing technological upgrades and solutions to address pain points in China's 5.4 trillion yuan physical retail market, offering integrated marketing, transaction, management, and revenue enhancement solutions for convenience stores and branded chain enterprises.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Machine learning models and training data, image and video data, sensor data, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
Samples of the dataset are as follows:
https://pan.baidu.com/s/1NjRFt8JO6GnDtIjLc8GFGA?pwd=587t
https://pan.baidu.com/s/1DZbJQUTpzj-T64MHZ_Mxmw?pwd=az56
https://pan.baidu.com/s/1Mm2R_nIm3tQZ8EFL3Xdtzg?pwd=xfb2
https://pan.baidu.com/s/1Qah8AA24XNWk37aTtdd8aA?pwd=h8p8
https://pan.baidu.com/s/1MOn4gklUjjMUIKmW6VF3Aw?pwd=b79g
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives

### How did you find your storage providers

Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03151449 CN
f03151456 CN
f03178077 US
f03178144 SG
f03178150 JP
f03178158 US
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Droplet client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by kevzak** [comment]
Hello - we see an application is open for this dataset in the FIDL Open Public pathway, we will proceed with this https://github.com/fidlabs/Open-Data-Pathway/issues/74
