### ISSUE TITLE
[DataCap Application] <Fogmeta Labs> - <Meta Ark> 

### ISSUE THREAD

**Issue by hengdingy** [fidlabs/Enterprise-Data-Pathway#8]
### Version

1

### DataCap Applicant

FogMeta

### What is your role related to the dataset

Dataset Owner

### Project ID

1968

### Data Owner Name

Fogmeta Labs

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

https://fogmetalabs.com/metaark

### Social Media Handle

FogMeta

### Social Media Type

Twitter

### Total amount of DataCap being requested

5PiB

### Unit for total amount of DataCap being requested

GiB

### Expected size of single dataset (one copy)

32GB

### Unit for expected size of single dataset

GiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

1PiB

### Unit for weekly allocation of DataCap requested

GiB

### On-chain address for first allocation

f1m5ysspdkkjhq2hb5sogit3j5snypexjqks5g6gi

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig

- [X] Use Custom Multisig

### Identifier

efil

### Share a brief history of your project and organization

```text
The research of Fogmeta Labs spans multiple levels from system technology, infrastructure, and middleware to services and solutions, and involves future systems, network technology and business, distributed systems and management, information management, and interactive and innovative services. Based on the views on and practices in the industry, Fogmeta also solves the problem of business complexity through operations optimization and other technologies.

Meta Ark is a data onboarding service provided by Fogmeta Labs for helping clients store their corporate datasets onto IPFS/Filecoin. Please refer to: https://fogmetalabs.com/metaark.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
Meta Ark is supported by FilSwan(https://www.filswan.com/).
```

### Describe the data being stored onto Filecoin

```text
These are private corporate datasets owned by our Meta Ark clients. Meta Ark is a data onboarding service provided by Fogmeta Labs for helping clients store their corporate datasets onto IPFS/Filecoin. Please refer to: https://fogmetalabs.com/metaark.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
Meta Ark is a data onboarding product developed by Fogmeta Labs. And the datasets come from our Meta Ark clients.
```

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We're going to use the `go-mc-sdk` to prepare the datasets. https://github.com/FogMeta/go-mc-sdk
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
We apologize, but due to confidentiality reasons, we are unable to disclose or share the private data here.
```

### Please share a sample of the data

```text
We apologize, but due to confidentiality reasons, we are unable to disclose or share the private data here.
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Others

### How did you find your storage providers

Slack, Partners, Others

### If you answered "Others" in the previous question, what is the tool or platform you used

```text
We plan to use FilSwan Platform (https://console.filswan.com/dashboard#/dashboard) for choosing storage providers who meet our requirements.
```

### Please list the provider IDs and location of the storage providers you will be working with.

```text
The storage providers we'd like to work with are presented below. Some of them are from the FilSwan Platform.
f03624
f010088
f02301
f08399
f02401
f0187709
f01163272
f01402814
f01072221
f0240185
f0143858
f01390330
f01225882
f0717969
f03223
f01395673
f01786736
f0836160
f032824
f01443744
f01871352
f01907556
f01946551
f02012951
f01970630
```

### How do you plan to make deals to your storage providers

Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
https://github.com/FogMeta/go-mc-sdk
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by kevzak** [comment]
Hi @hengdingy - the DataCap amounts entered are not correct.

**Comment by kevzak** [comment]
Also, as part of diligence please complete:

**Comment by kevzak** [comment]
Client never replied with required info, closing for now
