### ISSUE TITLE
[DataCap Application] <Organization> - <Project Name>

### ISSUE THREAD

**Issue by lyjmry** [fidlabs/Enterprise-Data-Pathway#84]
### Data Owner Name

深圳蒂爵Jewelry Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

Other

### Website

https://www.derier.com.cn/

### Social Media Handle

蒂爵珠宝Derier

### Social Media Type

WeChat

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

32PiB

### Expected size of single dataset (one copy)

4.5PiB

### Number of replicas to store

7

### Weekly allocation of DataCap requested

1000TiB

### On-chain address for first allocation

f1frdtz3yfldiqjwmpyu4kimgenol6tr26vfgvgrq

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
深圳蒂爵Jewelry Co., Ltd. was formerly known as 深圳蒂爵 Technology Co., Ltd.
, the company was established in 2001 and is mainly engaged in jewelry design, processing, manufacturing, trade and sales, etc. There are dozens of large jewelry sales stores in China alone. Due to the historical comparison of operating time, a large amount of data is generated, including design materials, operational data, store monitoring, etc.....
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
It mainly stores the company's design materials, surveillance videos, promotional materials and other content. Since the company was hacked, the control server was ransomed in BTC. The person in charge of the company contacted me and asked me to help him complete the backup on filecoin. I contacted several SPs who were willing to help the company store data for free.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
I will encrypt the data, then use a script to package it into a car file and provide it to the SP through hard drive transportation. We will issue orders through boost.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
yes ,https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1299

Since the company is engaged in the traditional physical industry and is not familiar with filecoin, their historical application was not successfully completed.
```

### Please share a sample of the data

```text
Promotional pictures and videos of DERIER jewelry products:
https://drive.google.com/drive/folders/1jk1ymtNcYRhwRK-_yKe67j1f1Bw13T2o
https://drive.google.com/drive/folders/1BMVSL0iOseVxbzUDEUT6zW2Z2_3q_Zhi
https://drive.google.com/drive/folders/1NsPWVUdtTEHyP1-iErS0DzWDNvjOGoJz

Honors received by DERIER: https://drive.google.com/drive/folders/1iwZmLFcD8nCqazwHGfWuI59x3KFr0oOq

DERIER designer's design draft and production pictures:
https://drive.google.com/drive/folders/1qtHHl4ffvMKxEGymFMO4fbHCbnFJ3gjn

Celebrities and models endorse DERIER:
https://drive.google.com/drive/folders/16Xq2stfWDQgmJaQpP0w8iidNW6MDLNUP
https://drive.google.com/drive/folders/1kAcDT0X_sDFneEnzuU4XLyjtUX9aI31B

Propaganda articles of DERIER:
https://drive.google.com/drive/folders/1qD1CLfvUz6huXXNL_kGwHk56VPHwHw4K

Data from DERIER Business School:
https://drive.google.com/drive/folders/1iRLzp8rmXIUyM4eUvyyG0ZKkgksnLa-R?usp=sharing

Real picture of DERIER store:
https://drive.google.com/drive/folders/1OLaC7-d4gTRyLe4Do2mbZwlrMBbW8wmV

Activities held by DERIER:
https://drive.google.com/drive/folders/1F6PpaeEwrmLzQGTTEMW3LKPfb0oep14m

9、TV plays and movies sponsored by DERIER:
https://drive.google.com/drive/folders/1o0HX9uZOD1wRYaVOvHumBs0KWlXbjKJK




10.https://drive.google.com/file/d/13CwZnaumnCNp0mD6z4FjlIOUlD_TNOuR/view?usp=drive_link


Data size proof.：https://drive.google.com/drive/folders/1YEDLJmJr3FWbAWqxPvOUxi0z67Yp14jY?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### If you chose not to confirm, what was the reason

```text
This data is corporate private and sensitive data.
```

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How did you find your storage providers

Slack, Others

### If you answered "Others" in the previous question, what is the tool or platform you used

```text
Wechat
offline
```

### Please list the provider IDs and location of the storage providers you will be working with.

```text
Chengdu f03216485,
Shenzhen f01660795,
Shandong Qingdao f01025366
Guangdong Shenzhen f03157905
Hong Kong f03220176
 Singapore f03220172
Sichuan Ya'an f03260592 (new)
 Sichuan Ziyang f02035256
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by martplo** [comment]
Hi @lyjmry,

Apologies for the delayed response, and thank you for submitting your application! Before we proceed, could you please review the [rules page of the allocator](https://github.com/fidlabs/Enterprise-Data-Pathway/wiki)?

Additionally, I need you to prepare a list of at least 5 Storage Providers (SPs) located in at least two different geopolitical regions.

Next Steps:
* KYC: Complete the Know Your Customer (KYC) process via allocator.tech using Gitcoin Passport.
* KYB: Fill out this [KYB form](https://form.jotform.com/242733516818057).
Please note that KYB checks via synps.io are currently unavailable. To proceed, feel free to contact me on Slack to arrange a video meeting. My Slack ID is U07KMEA79K6.

**Comment by lyjmry** [comment]
> Hi @lyjmry,
> 
> Apologies for the delayed response, and thank you for submitting your application! Before we proceed, could you please review the [rules page of the allocator](https://github.com/fidlabs/Enterprise-Data-Pathway/wiki)?
> 
> Additionally, I need you to prepare a list of at least 5 Storage Providers (SPs) located in at least two different geopolitical regions.
> 
> Next Steps:
> 
> * KYC: Complete the Know Your Customer (KYC) process via allocator.tech using Gitcoin Passport.
> * KYB: Fill out this [KYB form](https://form.jotform.com/242733516818057).
>   Please note that KYB checks via synps.io are currently unavailable. To proceed, feel free to contact me on Slack to arrange a video meeting. My Slack ID is U07KMEA79K6.



Hi Martplo ,Thank you for taking the time to follow and respond to my application.

1. kYC part: I have passed the certification in https://github.com/fidlabs/Open-Data-Pathway/issues/43.
2. Regarding SP (copy), I have selected more than 5 SPs in Greater China and Singapore.
3.Regarding the KYB part, I will fill out the form as required and contact you on slack to cooperate with further due diligence.

**Comment by lyjmry** [comment]
I have completed filling in the relevant information.

**Comment by martapiekarska** [comment]
Just to let you know, that we have moved into a process where DataCap allocated to you will go through a smart contract and will only be usable with SPs you name, so please carefully verify the SPs, there won't be a simple way of changing them out if you make a mistake

**Comment by lyjmry** [comment]
> Just to let you know, that we have moved into a process where DataCap allocated to you will go through a smart contract and will only be usable with SPs you name, so please carefully verify the SPs, there won't be a simple way of changing them out if you make a mistake

If after allocation, can other SPs be added? Because this data is large, more SPs may be needed to store it.

**Comment by martplo** [comment]
Yes, but you'll have to inform us beforehand.

**Comment by martplo** [comment]
@lyjmry 
>kYC part: I have passed the certification in https://github.com/fidlabs/Open-Data-Pathway/issues/43.

Since this is a new application with a new wallet address, please complete the requested KYC process using the provided wallet address.
Thank you

**Comment by lyjmry** [comment]
> @lyjmry
> 
> > kYC part: I have passed the certification in [fidlabs/Open-Data-Pathway#43](https://github.com/fidlabs/Open-Data-Pathway/issues/43).
> 
> Since this is a new application with a new wallet address, please complete the requested KYC process using the provided wallet address. Thank you

I don't quite understand what the purpose of this is? Why can't we KYC the gituhb account but the wallet address?

**Comment by lyjmry** [comment]
> @lyjmry,
> 
> > If only to verify that I am a real person, I think my previous verification has proved this.
> > Although I used a different wallet address, I used my KYC-passed and only Github account.
> 
> I completely appreciate that your previous KYC verification has already established your identity as a real person, and I also acknowledge that you’re using your verified GitHub account.
> 
> However, for compliance and security purposes, we require a separate KYC validation for each wallet address. This ensures that every wallet associated with an application is verified independently, which helps us maintain a secure and transparent system for everyone involved.
> 
> > In addition, to which email address do I need to submit the company's authorization letter, the company's business license, and the company's person in charge KYC related information?
> 
> You can send those to [mplocic@fidl.tech](mailto:mplocic@fidl.tech).

Please help to post the KYC link, thank you
![image](https://github.com/user-attachments/assets/9636c68d-ac7f-4870-adc2-86b2a9c47671)

**Comment by lyjmry** [comment]
> KYC has been requested. Please complete KYC at https://kyc.allocator.tech/?owner=fidlabs&repo=Enterprise-Data-Pathway&client=f1frdtz3yfldiqjwmpyu4kimgenol6tr26vfgvgrq&issue=84

Do I still need to purchase ETH for on-chain interaction gas?

**Comment by martplo** [comment]
@lyjmry,
KYC requested in above message. 

>Thank you. Is it possible to add nodes using the same SP? Because the hardware of a single node is bottlenecked, they need to add new nodes to accommodate more sectors.

You must also comply with the requirement of having at least 4 Storage Providers (SPs) in at least 2 different geopolitical regions.
This rule ensures that your application meets the necessary geographical distribution for security and compliance.

**Comment by lyjmry** [comment]
> @lyjmry, KYC requested in above message.
> 
> > Thank you. Is it possible to add nodes using the same SP? Because the hardware of a single node is bottlenecked, they need to add new nodes to accommodate more sectors.
> 
> You must also comply with the requirement of having at least 4 Storage Providers (SPs) in at least 2 different geopolitical regions. This rule ensures that your application meets the necessary geographical distribution for security and compliance.

Aren’t China and Singapore two geopolitical zones?

**Comment by lyjmry** [comment]
> @lyjmry,
> 
> > Do I still need to purchase ETH for on-chain interaction gas?
> 
> You have to reach a score of at least 20. If that requires on-chain transaction, then I'm afraid you have to pay for gas.

The address I applied for is the f1 address, but I saw that the interactive website uses the EVM address.

**Comment by martplo** [comment]
@lyjmry, 
>Aren’t China and Singapore two geopolitical zones?

It is.

**Comment by lyjmry** [comment]
> > @lyjmry,
> > > Do I still need to purchase ETH for on-chain interaction gas?
> > 
> > 
> > You have to reach a score of at least 20. If that requires on-chain transaction, then I'm afraid you have to pay for gas.
> 
> The address I applied for is the f1 address, but I saw that the interactive website uses the EVM address.

Are there any other good solutions besides this? I think this current solution is not friendly.

**Comment by martplo** [comment]
@lyjmry, 
Hello, I think we will get back to the KYC process if that's troubling you and instead move to the next step that I'm more concerned about. Here are further questions about your application:
1. It sounds like this dataset is not your property. Can you confirm that the data in this dataset is your property? If not, on whose behalf are you acting, and what authorization do you have to represent the data owner?
2. What is the source of this dataset? Were the data collected internally, or do they come from an external entity?
3. Based on the provided screenshots, the dataset size appears to be approximately 50TB, which differs from the declared 4.5PB. These screenshots do not seem to confirm the full dataset, and the content displayed may not necessarily reflect the actual data. Could you clarify whether all the data are relevant to the project, or if it might be possible to focus on a more targeted subset?
4. Are the data compliant with relevant legal regulations, such as GDPR or other local data protection laws?
5. Referring to point 3, the request for 32PiB seems to be significantly larger than what might reasonably be required. Could you review and suggest a smaller, more focused volume of data that would still meet the project’s needs?

**Comment by lyjmry** [comment]
> @lyjmry, Hello, I think we will get back to the KYC process if that's troubling you and instead move to the next step that I'm more concerned about. Here are further questions about your application:
> 
> 1. It sounds like this dataset is not your property. Can you confirm that the data in this dataset is your property? If not, on whose behalf are you acting, and what authorization do you have to represent the data owner?
> 2. What is the source of this dataset? Were the data collected internally, or do they come from an external entity?
> 3. Based on the provided screenshots, the dataset size appears to be approximately 50TB, which differs from the declared 4.5PB. These screenshots do not seem to confirm the full dataset, and the content displayed may not necessarily reflect the actual data. Could you clarify whether all the data are relevant to the project, or if it might be possible to focus on a more targeted subset?
> 4. Are the data compliant with relevant legal regulations, such as GDPR or other local data protection laws?
> 5. Referring to point 3, the request for 32PiB seems to be significantly larger than what might reasonably be required. Could you review and suggest a smaller, more focused volume of data that would still meet the project’s needs?


Thanks for the update.
1. Regarding my authority issue, I have notified the company to prepare a letter of authorization, which will be sent to the email address you provided together with the business license.
2. The source of this data set is the company’s operating data and design materials for more than 20 years, promotional videos, and surveillance videos of dozens of physical stores.
3. The screenshot is saved from 8 sets of 36 16T hard drives to a data volume (8*36*16=4608T). Taking into account the hard drive usage, it is actually close to 4.5PiB.
4. This data does not involve important national protected data, it is all the company’s data.
5. If possible, we can also apply in batches. The quota for each batch of applications is 8PiB, which can be completed in four batches. I will adjust the batches of data set preparation according to your ideas.

If you have a better proposal, you can tell me.
For example: How do you need us to cooperate with you to check the authenticity of the data set.

**Comment by lyjmry** [comment]
Hi @martplo , the company has sent the authorization letter and business license to the relevant email address.[mplocic@fidl.tech](mailto:mplocic@fidl.tech).thank you

**Comment by lyjmry** [comment]
Please update if there are new requirements.

**Comment by martplo** [comment]
@lyjmry, 
I didn't get any e-mail from you. So I'm waiting for that.

**Comment by lyjmry** [comment]
> Please update if there are new requirements.

![298b1a804a530c98a10bb623329e944](https://github.com/user-attachments/assets/0a48a839-3a34-40bd-b0a9-2831861cafcf)
The contact person for this company has been sent to you.

**Comment by martplo** [comment]
I checked, and it landed in my spam folder. I cannot retrieve it. Please send it to my Slack.

**Comment by martplo** [comment]
@lyjmry How will you ensure retrieval of specific data? With such a large amount of data, downloading 4.5 PiB each time will be impossible. So how will you prepare the data and provide information about where each part of the dataset is stored? I assume that since it is not your data, you will have to share such information with the data owner.

**Comment by lyjmry** [comment]
> [martplo](/martplo)
Yes, this is why most of the SPs I choose are from Greater China. We will encrypt the data locally and package it into car files, and then transfer it offline.

**Comment by lyjmry** [comment]
> @lyjmry How will you ensure retrieval of specific data? With such a large amount of data, downloading 4.5 PiB each time will be impossible. So how will you prepare the data and provide information about where each part of the dataset is stored? I assume that since it is not your data, you will have to share such information with the data owner.


Yes, this is why most of the SPs I choose are from Greater China. We will encrypt the data locally and package it into car files, and then transfer it offline.

**Comment by martplo** [comment]
>Yes, this is why most of the SPs I choose are from Greater China. We will encrypt the data locally and package it into car files, and then transfer it offline.

This doesn't explain how you will know where you store each piece. Are you preparing any explorer for that?

**Comment by lyjmry** [comment]
> > Yes, this is why most of the SPs I choose are from Greater China. We will encrypt the data locally and package it into car files, and then transfer it offline.
> 
> This doesn't explain how you will know where you store each piece. Are you preparing any explorer for that?

Our data has already been categorized and organized, so we only need to convert this data into car files sequentially and in batches, while recording the index relationship between car files and source data.
To illustrate with an example: we need to store surveillance video data from a certain store for November 2024. This batch of data is currently saved in our storage server under the directory "//mnt/disk17/*/2024-11". We just need to package and convert the surveillance videos in this directory into car files in order of their names. Every time we generate a car file, we record its corresponding piece CID and associated video information tags into a file named "surveillance-store-number-2024-11.csv", for example: baga6ea4seaqe6pxksytiswdbg2phlixkkimu4sgya3nwu4yvyhmrca3gsusjqbi, ddhhmm-ddhhmm, remark.
The CSV file serves as the lookup and retrieval archive for the data. We will enter it into our management system. When we need to retrieve data from the Filecoin network, we only need to first locate the corresponding CSV file, and then find the specific piece CID that needs to be retrieved from the CSV file.

**Comment by martplo** [comment]
Hi, @lyjmry,
Thank you for actively participating in our conversations and addressing additional questions. I also want to apologize for the delayed response due to the holiday break.

After careful consideration, we regret to inform you that your application has been rejected for the following reasons:

* You submitted two applications through our second pathway and received datacap for both, which may be seen as a violation by the watchdog. Especially since you actively get DC from those applications.
* The data you intend to store through this pathway does not belong to you. We have considered the data consent you shared with us, but this is something we would rather not do.
* The dataset does not provide significant value to the Filecoin network. 

We appreciate your efforts and hope you understand our decision.

**Comment by lyjmry** [comment]
Although I cannot ask you to further support my application, I am confused: Why does enterprise data need to be valuable to Filecoin when stored on Filecoin? I don’t know what the standard of this value is? Although I am not the owner of the data, I have received a commission from the enterprise.

**Comment by martplo** [comment]
In this case, dataset value is just an additional factor that is not decisive in rejecting this application. If this data were valuable, it would be a further argument to consider. I mentioned this just for the record.
